### ISSUE TITLE
Breaking Change in OpenTelemetry-Collector

### ISSUE THREAD

**Issue by hannahchiodo-msft** [git-ecosystem/trace2receiver#29]
This needs to be updated to match the newer versions of the OpenTelemetry Collector, starting in v0.106.0: https://github.com/open-telemetry/opentelemetry-collector/releases

We are unable to incorporate security fixes downstream in the collector until the trace2receiver is updated.

Errors seen when building our fork of the sample-trace2-otel-collector are as follows:
```
go\pkg\mod\github.com\git-ecosystem\trace2receiver@v0.5.5\rcvr_base.go:15:27: undefined: receiver.CreateSettings
go\pkg\mod\github.com\git-ecosystem\trace2receiver@v0.5.5\platform_windows.go:22:18: undefined: receiver.CreateSettings
go\pkg\mod\github.com\git-ecosystem\trace2receiver@v0.5.5\rcvr_namedpipe.go:47:63: undefined: component.NewFatalErrorEvent
```

**Comment by mpysson** [comment]
PR to address: #30

**Comment by dscho** [comment]
> PR to address: [#30](https://github.com/git-ecosystem/trace2receiver/pull/30)

This PR was merged.
